
POST http://localhost:3000/transactions
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaHMiLCJpYXQiOjE3MzAxMjU2NTh9.jZ4X84J_iVNYjzUa-lE7O_Lkwq3g5n799bc6HsuAzDo

{
    
    "type":"expense",
    "category":"wifi",
    "amount":3600,
    "date":"2024-10-10",
    "description":"wifi bill"
}
###
GET http://localhost:3000/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaHMiLCJpYXQiOjE3MzAxMjU2NTh9.jZ4X84J_iVNYjzUa-lE7O_Lkwq3g5n799bc6HsuAzDo

###

GET http://localhost:3000/transactions/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaHMiLCJpYXQiOjE3MzAxMjU2NTh9.jZ4X84J_iVNYjzUa-lE7O_Lkwq3g5n799bc6HsuAzDo

###


PUT http://localhost:3000/transactions/4
Content-Type:application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaHMiLCJpYXQiOjE3MzAxMjU2NTh9.jZ4X84J_iVNYjzUa-lE7O_Lkwq3g5n799bc6HsuAzDo



{
    
    
   "type":"INCOME",
    "category":"BUSINESS",
    "amount":50000,
    "date":"2024-10-19",
    "description":"Profit in Business" 
}
###

DELETE http://localhost:3000/transactions/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaHMiLCJpYXQiOjE3MzAxMjU2NTh9.jZ4X84J_iVNYjzUa-lE7O_Lkwq3g5n799bc6HsuAzDo

###

GET http://localhost:3000/summary
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdhbmVzaHMiLCJpYXQiOjE3MzAxMjU2NTh9.jZ4X84J_iVNYjzUa-lE7O_Lkwq3g5n799bc6HsuAzDo

###

POST http://localhost:3000/users/
Content-Type: application/json


{
    "username":"Ganeshs",
    "name":"ganesh",
    "password":"Ganeshkavi123",
    "gender":"Male",
    "location":"Hyderabad"

}
###
POST http://localhost:3000/login/
Content-Type: application/json 


{
    "username":"Ganeshs",
    "password":"Ganeshkavi123"
}
